### ISSUE TITLE
[bug] hydration mismatch

### ISSUE THREAD

**Issue by Hebilicious** [Hebilicious/form-actions-nuxt#31]
> * For the hydration mismatch this is probably a bug, do you have a repro ? With useFetch the data fetched on SSR is passed in the payload to the client (so you should see it in the nuxt devtools in Payload/Data)

Here's a minimal reproduction on stackblitz: https://stackblitz.com/edit/nuxt-starter-trga3p?file=components%2FBooks.vue
Again, same minimal code from README using ServerLoader, tested on nuxt `v3.6.5` + form-actions-nuxt `0.2.0-beta.1`.

<details>
<summary>Screenshot</summary>

![image](https://github.com/Hebilicious/form-actions-nuxt/assets/140389201/b26c1e8c-c22d-43bf-b68c-85a51de63a48)

</details>

You can see the `Hydration text mismatch` warning on the console.

Some interesting points:
- `console.log` inside the component is **run more than once on the server** (see lower left, console from terminal). Here you see it three times, but on my actual project I consistently see it twice.
- `console.log` on the client **does not return result value** -- see console on Chrome dev tools: `result.value: null`. I think this is where vue figures out there is a mismatch. One thing interesting is if you check the network request, you DO get a response with data in it. It seems like the data gets lost during returning it to the component. 
  Despite the node mismatch you can still see the rendered screen in the screenshot, but on the actual project the client fails to render the data. (Maybe its because on stackblitz the client also renders the component twice, but not the actual project.)

I'm also checking on the route params update as well. Stay tuned for feedbacks! :)

_Originally posted by @jangxyz in https://github.com/Hebilicious/form-actions-nuxt/discussions/29#discussioncomment-6687814_

**Comment by Hebilicious** [comment]
I was able to reproduce it initially, but as soon as I switched to `/pages` the bug went away. 

Still interesting that it happens with `app.vue`, but that's probably an upstream bug.

I did notice a couple of other bugs and will push fixes now 
https://github.com/Hebilicious/form-actions-nuxt/pull/32 
https://github.com/Hebilicious/form-actions-nuxt/pull/35

**Comment by jangxyz** [comment]
I can confirm that with the [v0.2.0-beta.4](https://github.com/Hebilicious/form-actions-nuxt/releases/tag/v0.2.0-beta.4) release, the mismatch is gone -- for both `pages/` and default `app.vue` approach. Great work! 😎
